- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Astra
  - Avrite
  - Delta
  - Paper
  - Silly
  - Spectrum
  - Amber
  - Bagel
  - Barratry
  - Box
  - Cog
  - Cluster
  - Core
  - Fland
  - Gemini
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Saltern
  - Train
  - Gate
  - Loop
  - Convex
  - Plasma
  - Reach
  # - Elkridge # remap in progress
