- type: job
  id: BorgSecurity
  name: job-name-borg-security
  description: job-description-borg-security
  playTimeTracker: JobBorgSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10800 # 3 hours
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-security-borg
  jobEntity: PlayerBorgChassisSecurity
  applyTraits: false
