- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours
    - !type:OverallPlaytimeRequirement
      time: 14400 # 4 hours
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-iaa
  canBeAntag: false
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: LawyerStampProvider
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 65
  #end-backmen: currency

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLaw
    socks: ClothingUnderwearSockLawyer
  inhand:
    - BriefcaseLawyerFilled
  storage:
    back:
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - HyperLinkBookSOPLaw
