# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
    - !type:DepartmentTimeRequirement
      department: Silicon
      time: 7200 # 2 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 7200 # 2 hours
    - !type:OverallPlaytimeRequirement
      time: 14400 # 4 hours
  weight: 18
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-crew
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # 6 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-crew
  jobEntity: PlayerBorgBattery
  applyTraits: false
