name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Дает доступ на добавление/удаление меток
      pull-requests: write  # Если действие применяется к PR
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      if: join(github.event.issue.labels) == ''
      with:
        labels: "S: Untriaged"
